BASE: ['']
TOOLBOX_MODE: "train_and_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 30
  LR: 9e-3
  MODEL_FILE_NAME: deepphys_train
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 30
    DATASET: MultiDataset
    MULTI_DATASET: ["UBFC-rPPG", "UBFC-rPPG1", "PURE", "COHFACE", "VICARPPG2"]
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NCDHW
    MULTI_PATH: ["RawData/UBFC_DATASET/DATASET_2", "RawData/UBFC_DATASET/DATASET_1", "RawData/PURE", "RawData/cohface/RawData", "RawData/VicarPPG-2"]                   # Raw dataset path, need to be updated
    CACHED_PATH: "PreprocessedData"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.5
    PREPROCESS:
      DATA_TYPE: ['Raw']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'RF'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.3
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 144
        W: 144
VALID:
  DATA:
    FS: 30
    DATASET: MultiDataset
    MULTI_DATASET: ["UBFC-rPPG", "PURE", "COHFACE", "VICARPPG2"]
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NCDHW
    MULTI_PATH: ["RawData/UBFC_DATASET/DATASET_2", "RawData/PURE", "RawData/cohface/RawData", "RawData/VicarPPG-2"]                 # Raw dataset path, need to be updated
    CACHED_PATH: "PreprocessedData"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.5
    END: 0.6
    PREPROCESS:
      DATA_TYPE: ['Raw']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'RF'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.3
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 144
        W: 144
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'DTW', 'BA']
  USE_LAST_EPOCH: False                      # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: MultiDataset
    MULTI_DATASET: ["UBFC-rPPG", "UBFC-rPPG1", "PURE", "COHFACE", "VICARPPG2"]
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NCDHW
    MULTI_PATH: ["RawData/UBFC_DATASET/DATASET_2", "RawData/UBFC_DATASET/DATASET_1", "RawData/PURE", "RawData/cohface/RawData", "RawData/VicarPPG-2"]                   # Raw dataset path, need to be updated
    CACHED_PATH: "PreprocessedData"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.6
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Raw']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'RF'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.3
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 144
        W: 144
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: APNET
  SECONDARY_PREPROCESS: True
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  MODEL_PATH:   ""